var createDoomModule=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var h=moduleArg;h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;"undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a||async function(b){async function c(n,q){h.dataFileDownloads||(h.dataFileDownloads={});try{var r=await fetch(n)}catch(I){throw Error(`Network Error: ${n}`,{e:I});}if(!r.ok)throw Error(`${r.status}: ${r.url}`);const y=[];q=Number(r.headers.get("Content-Length")||q);let B=0;h.setStatus&&h.setStatus("Downloading data...");for(r=r.body.getReader();;){var {done:J,
value:G}=await r.read();if(J)break;y.push(G);B+=G.length;h.dataFileDownloads[n]={loaded:B,total:q};let I=0,U=0;for(var R of Object.values(h.dataFileDownloads))I+=R.loaded,U+=R.total;h.setStatus&&h.setStatus(`Downloading data... (${I}/${U})`)}n=new Uint8Array(y.map(I=>I.length).reduce((I,U)=>I+U,0));R=0;for(const I of y)n.set(I,R),R+=I.length;return n.buffer}async function d(n){for(var q of b.files)n.addRunDependency(`fp ${q.filename}`);n.addRunDependency("datafile_doomgeneric.data");n.preloadResults||
(n.preloadResults={});n.preloadResults["doomgeneric.data"]={kh:!1};l||=await g;(async function(r){if(!r)throw Error("Loading data file failed.");if(r.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+r.constructor.name);r=new Uint8Array(r);for(var y of b.files){var B=y.filename;n.FS_createDataFile(B,null,r.subarray(y.start,y.end),!0,!0,!0);n.removeRunDependency(`fp ${B}`)}n.removeRunDependency("datafile_doomgeneric.data")})(l)}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,
window.location.pathname.lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var e=h.locateFile?h.locateFile("doomgeneric.data",""):"doomgeneric.data",f=b.remote_package_size,g,l=h.getPreloadedPackage&&h.getPreloadedPackage(e,f);l||(g=c(e,f));h.calledRun?d(h):(h.preRun||(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/doom1.wad",start:0,end:28795076}],remote_package_size:28795076})})();
var aa=[],ba="./this.program",ca="",da;try{ca=(new URL(".",_scriptName)).href}catch{}da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var ea=console.log.bind(console),k=console.error.bind(console),fa,ha=!1,ia,ja,ka,la=!1;
function ma(){var a=na.buffer;m=new Int8Array(a);oa=new Int16Array(a);p=new Uint8Array(a);pa=new Uint16Array(a);t=new Int32Array(a);u=new Uint32Array(a);v=new Float32Array(a);w=new Float64Array(a);qa=new BigInt64Array(a);new BigUint64Array(a)}function x(a){h.onAbort?.(a);a=`Aborted(${a})`;k(a);ha=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ka?.(a);throw a;}var ra;
async function sa(a){if(!fa)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==ra&&fa)a=new Uint8Array(fa);else throw"both async and sync fetching of the wasm failed";return a}async function ta(a,b){try{var c=await sa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),x(d)}}
async function ua(a){var b=ra;if(!fa)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ta(b,a)}class va{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var oa,t,qa,m,v,w,pa,u,p,wa=a=>{for(;0<a.length;)a.shift()(h)},xa=[],ya=[],za=()=>{var a=h.preRun.shift();ya.push(a)},Aa=!0;
function Ba(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":m[a]=b;break;case "i8":m[a]=b;break;case "i16":oa[a>>1]=b;break;case "i32":t[a>>2]=b;break;case "i64":qa[a>>3]=BigInt(b);break;case "float":v[a>>2]=b;break;case "double":w[a>>3]=b;break;case "*":u[a>>2]=b;break;default:x(`invalid type for setValue: ${c}`)}}
var Ca=[],z=a=>{var b=Ca[a];b||(Ca[a]=b=Da.get(a));return b},Fa=()=>{var a=t[+Ea>>2];Ea+=4;return a},Ga=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ha=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ga(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ia=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ja=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ka=(a,b)=>Ha(a+"/"+b),La=()=>a=>(crypto.getRandomValues(a),0),Ma=a=>(Ma=La())(a),Na=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:A.Se();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ga(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Oa=(a,b)=>{function c(g){for(var l=0;l<
g.length&&""===g[l];l++);for(var n=g.length-1;0<=n&&""===g[n];n--);return l>n?[]:g.slice(l,n-l+1)}a=Na(a).slice(1);b=Na(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Pa=globalThis.TextDecoder&&new TextDecoder,C=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Pa)return Pa.decode(a.subarray(b,d));for(c="";b<d;){var e=
a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},Qa=[],Ra=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},D=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=
0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Sa=a=>{var b=Array(Ra(a)+1);a=D(a,b,0,b.length);b.length=a;return b},Ta=[];function Ua(a,b){Ta[a]={input:[],output:[],te:b};Va(a,Wa)}
var Wa={open(a){var b=Ta[a.node.Le];if(!b)throw new A.Pd(43);a.Td=b;a.seekable=!1},close(a){a.Td.te.Ue(a.Td)},Ue(a){a.Td.te.Ue(a.Td)},read(a,b,c,d){if(!a.Td||!a.Td.te.Of)throw new A.Pd(60);for(var e=0,f=0;f<d;f++){try{var g=a.Td.te.Of(a.Td)}catch(l){throw new A.Pd(29);}if(void 0===g&&0===e)throw new A.Pd(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.pe=Date.now());return e},write(a,b,c,d){if(!a.Td||!a.Td.te.uf)throw new A.Pd(60);try{for(var e=0;e<d;e++)a.Td.te.uf(a.Td,b[c+e])}catch(f){throw new A.Pd(29);
}d&&(a.node.ce=a.node.$d=Date.now());return e}},Xa={Of(){a:{if(!Qa.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Qa=Sa(a)}a=Qa.shift()}return a},uf(a,b){null===b||10===b?(ea(C(a.output)),a.output=[]):0!=b&&a.output.push(b)},Ue(a){0<a.output?.length&&(ea(C(a.output)),a.output=[])},zg(){return{Ug:25856,Wg:5,Tg:191,Vg:35387,Sg:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ag(){return 0},Bg(){return[24,
80]}},Ya={uf(a,b){null===b||10===b?(k(C(a.output)),a.output=[]):0!=b&&a.output.push(b)},Ue(a){0<a.output?.length&&(k(C(a.output)),a.output=[])}},E={oe:null,Vd(){return E.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=24576===(c&61440))||(e=4096===(c&61440));if(e)throw new A.Pd(63);E.oe||(E.oe={dir:{node:{ie:E.Qd.ie,me:E.Qd.me,Ae:E.Qd.Ae,re:E.Qd.re,He:E.Qd.He,Fe:E.Qd.Fe,De:E.Qd.De,Me:E.Qd.Me,ze:E.Qd.ze},stream:{be:E.Rd.be}},file:{node:{ie:E.Qd.ie,me:E.Qd.me},stream:{be:E.Rd.be,read:E.Rd.read,
write:E.Rd.write,Ge:E.Rd.Ge,Ke:E.Rd.Ke}},link:{node:{ie:E.Qd.ie,me:E.Qd.me,ye:E.Qd.ye},stream:{}},Jf:{node:{ie:E.Qd.ie,me:E.Qd.me},stream:A.dg}});c=A.createNode(a,b,c,d);F(c.mode)?(c.Qd=E.oe.dir.node,c.Rd=E.oe.dir.stream,c.Sd={}):A.isFile(c.mode)?(c.Qd=E.oe.file.node,c.Rd=E.oe.file.stream,c.Yd=0,c.Sd=E.mg??(E.mg=new Uint8Array(0))):40960===(c.mode&61440)?(c.Qd=E.oe.link.node,c.Rd=E.oe.link.stream):8192===(c.mode&61440)&&(c.Qd=E.oe.Jf.node,c.Rd=E.oe.Jf.stream);c.pe=c.ce=c.$d=Date.now();a&&(a.Sd[b]=
c,a.pe=a.ce=a.$d=c.pe);return c},Qd:{ie(a){var b={};b.lg=8192===(a.mode&61440)?a.id:1;b.yg=a.id;b.mode=a.mode;b.Eg=1;b.uid=0;b.vg=0;b.Le=a.Le;F(a.mode)?b.size=4096:A.isFile(a.mode)?b.size=a.Yd:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.pe=new Date(a.pe);b.ce=new Date(a.ce);b.$d=new Date(a.$d);b.cg=4096;b.Hf=Math.ceil(b.size/b.cg);return b},me(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Yd!=b&&(c=a.Sd,a.Sd=new Uint8Array(b),a.Sd.set(c.subarray(0,
Math.min(b,a.Yd))),a.Yd=b))},Ae(){E.ef||(E.ef=new A.Pd(44),E.ef.stack="<generic error, no stack>");throw E.ef;},re(a,b,c,d){return E.createNode(a,b,c,d)},He(a,b,c){try{var d=Za(b,c)}catch(f){}if(d){if(F(a.mode))for(var e in d.Sd)throw new A.Pd(55);$a(d)}delete a.parent.Sd[a.name];b.Sd[c]=a;a.name=c;b.$d=b.ce=a.parent.$d=a.parent.ce=Date.now()},Fe(a,b){delete a.Sd[b];a.$d=a.ce=Date.now()},De(a,b){var c=Za(a,b),d;for(d in c.Sd)throw new A.Pd(55);delete a.Sd[b];a.$d=a.ce=Date.now()},Me(a){return[".",
"..",...Object.keys(a.Sd)]},ze(a,b,c){a=E.createNode(a,b,41471,0);a.link=c;return a},ye(a){if(40960!==(a.mode&61440))throw new A.Pd(28);return a.link}},Rd:{read(a,b,c,d,e){if(e>=a.node.Yd)return 0;d=Math.min(a.node.Yd-e,d);b.set(a.node.Sd.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===m.buffer&&(f=!1);if(!d)return 0;a=a.node;a.ce=a.$d=Date.now();if(f)a.Sd=b.subarray(c,c+d),a.Yd=d;else if(0===a.Yd&&0===e)a.Sd=b.slice(c,c+d),a.Yd=d;else{f=e+d;var g=a.Sd.length;g>=f||(f=Math.max(f,g*(1048576>
g?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.Sd.subarray(0,a.Yd),a.Sd=new Uint8Array(f),a.Sd.set(g));a.Sd.set(b.subarray(c,c+d),e);a.Yd=Math.max(a.Yd,e+d)}return d},be(a,b,c){1===c?b+=a.position:2===c&&A.isFile(a.node.mode)&&(b+=a.node.Yd);if(0>b)throw new A.Pd(28);return b},Ge(a,b,c,d,e){if(!A.isFile(a.node.mode))throw new A.Pd(43);a=a.node.Sd;if(e&2||a.buffer!==m.buffer){d=!0;x();e=void 0;if(!e)throw new A.Pd(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);m.set(a,e)}}else d=!1,e=a.byteOffset;return{Ch:e,Mg:d}},Ke(a,b,c,d){E.Rd.write(a,b,0,d,c,!1);return 0}}},ab=a=>{"string"==typeof a&&(a=Sa(a));a.subarray||(a=new Uint8Array(a));return a},bb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},cb=async a=>{a=await da(a);return new Uint8Array(a)},db=0,eb=null,fb=()=>{db--;h.monitorRunDependencies?.(db);if(0==db&&eb){var a=eb;eb=null;a()}},gb=()=>{db++;h.monitorRunDependencies?.(db)},hb=[],kb=async(a,b)=>{"undefined"!=typeof ib&&jb();for(var c of hb)if(c.canHandle(b))return c.handle(a,
b);return a},mb=async(a,b,c,d,e,f,g,l)=>{var n=b?Na(Ha(a+"/"+b)):a,q=`cp ${n}`;gb(q);try{var r=c;"string"==typeof c&&(r=await cb(c));r=await kb(r,n);l?.();f||lb(a,b,r,d,e,g)}finally{fb(q)}};function Va(a,b){A.Lf[a]={Rd:b}}function F(a){return 16384===(a&61440)}function Za(a,b){var c=F(a.mode)?(c=nb(a,"x"))?c:a.Qd.Ae?0:2:54;if(c)throw new A.Pd(c);for(c=A.se[ob(a.id,b)];c;c=c.Ce){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return A.Ae(a,b)}
function $a(a){var b=ob(a.parent.id,a.name);if(A.se[b]===a)A.se[b]=a.Ce;else for(b=A.se[b];b;){if(b.Ce===a){b.Ce=a.Ce;break}b=b.Ce}}function lb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:pb(a),g=b?Ha(a+"/"+b):a);a=bb(d,e);g=A.create(g,a);c&&(c=ab(c),qb(g,a|146),b=A.open(g,577),A.write(b,c,0,c.length,0,f),A.close(b),qb(g,a))}
function H(a,b={}){if(!a)throw new A.Pd(44);b.Te??(b.Te=!0);"/"===a.charAt(0)||(a=A.Se()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(l=>!!l);for(var d=A.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Ia(e),A.nf(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ha(e+"/"+a[f]);try{d=Za(d,a[f])}catch(l){if(44===l?.Wd&&g&&b.Fg)return{path:e};throw l;}!d.ke||g&&!b.Te||(d=d.ke.root);if(40960===(d.mode&61440)&&(!g||
b.he)){if(!d.Qd.ye)throw new A.Pd(52);d=d.Qd.ye(d);"/"===d.charAt(0)||(d=Ia(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new A.Pd(32);}function pb(a){for(var b;;){if(A.nf(a))return a=a.Vd.Sf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function ob(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%A.se.length}function rb(a){var b=ob(a.parent.id,a.name);a.Ce=A.se[b];A.se[b]=a}
function nb(a,b){return A.Pf?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function sb(a,b){if(!F(a.mode))return 54;try{return Za(a,b),20}catch(c){}return nb(a,"wx")}function tb(a,b,c){try{var d=Za(a,b)}catch(e){return e.Wd}if(a=nb(a,"wx"))return a;if(c){if(!F(d.mode))return 54;if(A.nf(d)||pb(d)===A.Se())return 10}else if(F(d.mode))return 31;return 0}function ub(a,b){if(!a)throw new A.Pd(b);return a}
function K(a){a=A.ug(a);if(!a)throw new A.Pd(8);return a}function vb(a,b=-1){a=Object.assign(new A.$f,a);if(-1==b)a:{for(b=0;b<=A.ag;b++)if(!A.streams[b])break a;throw new A.Pd(33);}a.fd=b;return A.streams[b]=a}function wb(a,b=-1){a=vb(a,b);a.Rd?.eh?.(a);return a}function xb(a,b,c){var d=a?.Rd.me;a=d?a:b;d??=b.Qd.me;ub(d,63);d(a,c)}function yb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Je)}return b}
function zb(a){var b={Rg:4096,lh:4096,Hf:1E6,Qg:5E5,Pg:5E5,files:A.sf,ih:A.sf-1,mh:42,flags:2,zh:255};a.Qd.Vf&&Object.assign(b,a.Qd.Vf(a.Vd.Gg.root));return b}function L(a,b=511){return A.re(a,b&1023|16384,0)}function Ab(a,b,c){"undefined"==typeof c&&(c=b,b=438);return A.re(a,b|8192,c)}function Bb(a,b,c,d){xb(a,b,{mode:c&4095|b.mode&-4096,$d:Date.now(),Mf:d})}function qb(a,b,c){a="string"==typeof a?H(a,{he:!c}).node:a;Bb(null,a,b,c)}
function Cb(a,b,c){if(F(b.mode))throw new A.Pd(31);if(!A.isFile(b.mode))throw new A.Pd(28);var d=nb(b,"w");if(d)throw new A.Pd(d);xb(a,b,{size:c,timestamp:Date.now()})}function Db(a,b){a="string"==typeof a?a:pb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ha(a+"/"+c);try{L(d)}catch(e){if(20!=e.Wd)throw e;}a=d}}return d}function Eb(a,b,c,d){a="string"==typeof a?a:pb(a);b=Ha(a+"/"+b);return A.create(b,bb(c,d))}
function Fb(a){if(!(a.Cg||a.Dg||a.link||a.Sd))if(globalThis.XMLHttpRequest)x("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Sd=(void 0)(a.url)}catch(b){throw new A.Pd(29);}}
function Hb(a,b,c,d,e){class f{bf=!1;de=[];af=void 0;Df=0;Cf=0;get(q){if(!(q>this.length-1||0>q)){var r=q%this.Ff;return this.af(q/this.Ff|0)[r]}}bg(q){this.af=q}Ef(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);200<=q.status&&300>q.status||304===q.status||x("Couldn't load "+c+". Status: "+q.status);var r=Number(q.getResponseHeader("Content-length")),y,B=(y=q.getResponseHeader("Accept-Ranges"))&&"bytes"===y;q=(y=q.getResponseHeader("Content-Encoding"))&&"gzip"===y;var J=1048576;B||(J=
r);var G=this;G.bg(R=>{var I=R*J,U=(R+1)*J-1;U=Math.min(U,r-1);if("undefined"==typeof G.de[R]){var Gb=G.de;I>U&&x("invalid range ("+I+", "+U+") or no bytes requested!");U>r-1&&x("only "+r+" bytes available! programmer error!");var O=new XMLHttpRequest;O.open("GET",c,!1);r!==J&&O.setRequestHeader("Range","bytes="+I+"-"+U);O.responseType="arraybuffer";O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);200<=O.status&&300>O.status||304===O.status||x("Couldn't load "+
c+". Status: "+O.status);I=void 0!==O.response?new Uint8Array(O.response||[]):Sa(O.responseText||"");Gb[R]=I}"undefined"==typeof G.de[R]&&x("doXHR failed!");return G.de[R]});if(q||!r)J=r=1,J=r=this.af(0).length,ea("LazyFiles on gzip forces download of the whole file when length is accessed");this.Df=r;this.Cf=J;this.bf=!0}get length(){this.bf||this.Ef();return this.Df}get Ff(){this.bf||this.Ef();return this.Cf}}if(globalThis.XMLHttpRequest){x("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var g=new f;var l=void 0}else l=c,g=void 0;var n=Eb(a,b,d,e);g?n.Sd=g:l&&(n.Sd=null,n.url=l);Object.defineProperties(n,{Yd:{get:function(){return this.Sd.length}}});a={};for(const [q,r]of Object.entries(n.Rd))a[q]=(...y)=>{Fb(n);return r(...y)};a.read=(q,r,y,B,J)=>{Fb(n);q=q.node.Sd;if(J>=q.length)r=0;else{B=Math.min(q.length-J,B);if(q.slice)for(var G=0;G<B;G++)r[y+G]=q[J+G];else for(G=0;G<B;G++)r[y+G]=q.get(J+G);r=B}return r};a.Ge=()=>{Fb(n);x();throw new A.Pd(48);};n.Rd=a;return n}
var A={root:null,Je:[],Lf:{},streams:[],sf:1,se:null,Kf:"/",lf:!1,Pf:!0,rg:null,$e:0,Pd:class{name="ErrnoError";constructor(a){this.Wd=a}},$f:class{de={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.de.flags}set flags(a){this.de.flags=a}get position(){return this.de.position}set position(a){this.de.position=a}},Zf:class{Qd={};Rd={};ke=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Vd=a.Vd;this.id=A.sf++;this.name=b;this.mode=c;this.Le=d;this.pe=
this.ce=this.$d=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Dg(){return F(this.mode)}get Cg(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new A.Zf(a,b,c,d);rb(a);return a},nf(a){return a===a.parent},isFile(a){return 32768===(a&61440)},qh(a){return 49152===(a&49152)},ag:4096,ug:a=>A.streams[a],dg:{open(a){a.Rd=A.tg(a.node.Le).Rd;a.Rd.open?.(a)},
be(){throw new A.Pd(70);}},qf:a=>a>>8,vh:a=>a&255,Be:(a,b)=>a<<8|b,tg:a=>A.Lf[a],Wf(a,b){function c(l){A.$e--;return b(l)}function d(l){if(l){if(!d.og)return d.og=!0,c(l)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);A.$e++;1<A.$e&&k(`warning: ${A.$e} FS.syncfs operations in flight at once, probably just doing extra work`);var e=yb(A.root.Vd),f=0,g;for(g of e)g.type.Wf?g.type.Wf(g,a,d):d(null)},Vd(a,b,c){var d="/"===c;if(d&&A.root)throw new A.Pd(10);if(!d&&c){var e=H(c,{Te:!1});c=e.path;
e=e.node;if(e.ke)throw new A.Pd(10);if(!F(e.mode))throw new A.Pd(54);}b={type:a,Gg:b,Sf:c,Je:[]};a=a.Vd(b);a.Vd=b;b.root=a;d?A.root=a:e&&(e.ke=b,e.Vd&&e.Vd.Je.push(b));return a},Jh(a){a=H(a,{Te:!1});if(!a.node.ke)throw new A.Pd(28);a=a.node;var b=a.ke,c=yb(b);for([,e]of Object.entries(A.se))for(;e;){var d=e.Ce;c.includes(e.Vd)&&$a(e);var e=d}a.ke=null;a.Vd.Je.splice(a.Vd.Je.indexOf(b),1)},Ae(a,b){return a.Qd.Ae(a,b)},re(a,b,c){var d=H(a,{parent:!0}).node;a=Ja(a);if(!a)throw new A.Pd(28);if("."===
a||".."===a)throw new A.Pd(20);var e=sb(d,a);if(e)throw new A.Pd(e);if(!d.Qd.re)throw new A.Pd(63);return d.Qd.re(d,a,b,c)},Vf(a){return zb(H(a,{he:!0}).node)},Hh(a){return zb(a.node)},create(a,b=438){return A.re(a,b&4095|32768,0)},xh(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{L(d,b)}catch(f){if(20!=f.Wd)throw f;}}},ze(a,b){if(!Na(a))throw new A.Pd(44);var c=H(b,{parent:!0}).node;if(!c)throw new A.Pd(44);b=Ja(b);var d=sb(c,b);if(d)throw new A.Pd(d);if(!c.Qd.ze)throw new A.Pd(63);
return c.Qd.ze(c,b,a)},He(a,b){var c=Ia(a),d=Ia(b),e=Ja(a),f=Ja(b);var g=H(a,{parent:!0});var l=g.node;g=H(b,{parent:!0});g=g.node;if(!l||!g)throw new A.Pd(44);if(l.Vd!==g.Vd)throw new A.Pd(75);var n=Za(l,e);a=Oa(a,d);if("."!==a.charAt(0))throw new A.Pd(28);a=Oa(b,c);if("."!==a.charAt(0))throw new A.Pd(55);try{var q=Za(g,f)}catch(r){}if(n!==q){b=F(n.mode);if(e=tb(l,e,b))throw new A.Pd(e);if(e=q?tb(g,f,b):sb(g,f))throw new A.Pd(e);if(!l.Qd.He)throw new A.Pd(63);if(n.ke||q&&q.ke)throw new A.Pd(10);
if(g!==l&&(e=nb(l,"w")))throw new A.Pd(e);$a(n);try{l.Qd.He(n,g,f),n.parent=g}catch(r){throw r;}finally{rb(n)}}},De(a){var b=H(a,{parent:!0}).node;a=Ja(a);var c=Za(b,a),d=tb(b,a,!0);if(d)throw new A.Pd(d);if(!b.Qd.De)throw new A.Pd(63);if(c.ke)throw new A.Pd(10);b.Qd.De(b,a);$a(c)},Me(a){a=H(a,{he:!0}).node;return ub(a.Qd.Me,54)(a)},Fe(a){var b=H(a,{parent:!0}).node;if(!b)throw new A.Pd(44);a=Ja(a);var c=Za(b,a),d=tb(b,a,!1);if(d)throw new A.Pd(d);if(!b.Qd.Fe)throw new A.Pd(63);if(c.ke)throw new A.Pd(10);
b.Qd.Fe(b,a);$a(c)},ye(a){a=H(a).node;if(!a)throw new A.Pd(44);if(!a.Qd.ye)throw new A.Pd(28);return a.Qd.ye(a)},stat(a,b){a=H(a,{he:!b}).node;return ub(a.Qd.ie,63)(a)},nh(a){var b=K(a);a=b.node;var c=b.Rd.ie;b=c?b:a;c??=a.Qd.ie;ub(c,63);return c(b)},uh(a){return A.stat(a,!0)},rh(a,b){qb(a,b,!0)},gh(a,b){a=K(a);Bb(a,a.node,b,!1)},sh(a){a="string"==typeof a?H(a,{he:!1}).node:a;xb(null,a,{timestamp:Date.now(),Mf:!0})},hh(a){a=K(a);xb(a,a.node,{timestamp:Date.now(),Mf:!1})},truncate(a,b){if(0>b)throw new A.Pd(28);
a="string"==typeof a?H(a,{he:!0}).node:a;Cb(null,a,b)},oh(a,b){a=K(a);if(0>b||0===(a.flags&2097155))throw new A.Pd(28);Cb(a,a.node,b)},Kh(a,b,c){a=H(a,{he:!0}).node;ub(a.Qd.me,63)(a,{pe:b,ce:c})},open(a,b,c=438){if(""===a)throw new A.Pd(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var f=H(a,{he:!(b&131072),Fg:!0});d=
f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new A.Pd(20);}else{if(e)throw new A.Pd(31);d=A.re(a,c|511,0);f=!0}if(!d)throw new A.Pd(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!F(d.mode))throw new A.Pd(54);if(!f&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=F(d.mode)&&("r"!==e||b&576)?31:nb(d,e)):e=44,e))throw new A.Pd(e);b&512&&!f&&A.truncate(d,0);b&=-131713;b=vb({node:d,path:pb(d),flags:b,seekable:!0,position:0,Rd:d.Rd,Kg:[],error:!1});b.Rd.open&&b.Rd.open(b);
f&&qb(d,c&511);return b},close(a){if(null===a.fd)throw new A.Pd(8);a.jf&&(a.jf=null);try{a.Rd.close&&a.Rd.close(a)}catch(b){throw b;}finally{A.streams[a.fd]=null}a.fd=null},be(a,b,c){if(null===a.fd)throw new A.Pd(8);if(!a.seekable||!a.Rd.be)throw new A.Pd(70);if(0!=c&&1!=c&&2!=c)throw new A.Pd(28);a.position=a.Rd.be(a,b,c);a.Kg=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new A.Pd(28);if(null===a.fd)throw new A.Pd(8);if(1===(a.flags&2097155))throw new A.Pd(8);if(F(a.node.mode))throw new A.Pd(31);
if(!a.Rd.read)throw new A.Pd(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new A.Pd(70);b=a.Rd.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new A.Pd(28);if(null===a.fd)throw new A.Pd(8);if(0===(a.flags&2097155))throw new A.Pd(8);if(F(a.node.mode))throw new A.Pd(31);if(!a.Rd.write)throw new A.Pd(28);a.seekable&&a.flags&1024&&A.be(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new A.Pd(70);b=a.Rd.write(a,
b,c,d,e,f);g||(a.position+=b);return b},Ge(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new A.Pd(2);if(1===(a.flags&2097155))throw new A.Pd(2);if(!a.Rd.Ge)throw new A.Pd(43);if(!b)throw new A.Pd(28);return a.Rd.Ge(a,b,c,d,e)},Ke(a,b,c,d,e){return a.Rd.Ke?a.Rd.Ke(a,b,c,d,e):0},mf(a,b,c){if(!a.Rd.mf)throw new A.Pd(59);return a.Rd.mf(a,b,c)},Eh(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&x(`Invalid encoding type "${b.encoding}"`);
var c=A.open(a,b.flags);a=A.stat(a).size;var d=new Uint8Array(a);A.read(c,d,0,a,0);"utf8"===b.encoding&&(d=C(d));A.close(c);return d},Lh(a,b,c={}){c.flags=c.flags||577;a=A.open(a,c.flags,c.mode);b=ab(b);A.write(a,b,0,b.byteLength,void 0,c.Xg);A.close(a)},Se:()=>A.Kf,Yg(a){a=H(a,{he:!0});if(null===a.node)throw new A.Pd(44);if(!F(a.node.mode))throw new A.Pd(54);var b=nb(a.node,"x");if(b)throw new A.Pd(b);A.Kf=a.path},Dh(){A.lf=!1;for(var a of A.streams)a&&A.close(a)},jh(a,b){try{var c=H(a,{he:!b});
a=c.path}catch(f){}var d=!1,e=null;try{c=H(a,{parent:!0}),Ja(a),c=H(a,{he:!b}),d=!0,e=c.node}catch(f){}return d?e:null},ve(a,b,c,d){a=Ka("string"==typeof a?a:pb(a),b);b=bb(!!c,!!d);var e;(e=A.ve).qf??(e.qf=64);e=A.Be(A.ve.qf++,0);Va(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,n){for(var q=0,r=0;r<n;r++){try{var y=c()}catch(B){throw new A.Pd(29);}if(void 0===y&&0===q)throw new A.Pd(6);if(null===y||void 0===y)break;q++;g[l+r]=y}q&&(f.node.pe=Date.now());return q},write(f,
g,l,n){for(var q=0;q<n;q++)try{d(g[l+q])}catch(r){throw new A.Pd(29);}n&&(f.node.ce=f.node.$d=Date.now());return q}});return Ab(a,b,e)}};function Ib(a,b){if("/"===b.charAt(0))return b;a=-100===a?A.Se():K(a).path;if(0==b.length)throw new A.Pd(44);return a+"/"+b}var Ea=void 0,Jb=0,Kb={},Lb=a=>{if(a instanceof va||"unwind"==a)return ia;throw a;},Mb=a=>{ia=a;Aa||0<Jb||(h.onExit?.(a),ha=!0);throw new va(a);},Nb=()=>{if(!(Aa||0<Jb))try{var a=ia;ia=a;Mb(a)}catch(b){Lb(b)}},Ob=a=>{if(!ha)try{a()}catch(b){Lb(b)}finally{Nb()}};
function Pb(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement}var Qb=a=>{setTimeout(()=>{Ob(a)},1E4)},Rb=!1,Sb=[];
function jb(){function a(){Rb=document.pointerLockElement===h.canvas}if(!Tb){Tb=!0;hb.push({canHandle:c=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:Ub(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:Ub(d)}));var f=URL.createObjectURL(e);return new Promise((g,l)=>{var n=new Image;n.onload=()=>{var q=document.createElement("canvas");q.width=n.width;q.height=n.height;q.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(f);
g(c)};n.onerror=()=>{k(`Image ${f} could not be decoded`);l()};n.src=f})}});hb.push({canHandle:c=>!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,l=URL.createObjectURL(new Blob([c],{type:Ub(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=()=>{if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var q="",r=0,y=0,B=0;B<c.length;B++)for(r=r<<
8|c[B],y+=8;6<=y;){var J=r>>y-6&63;y-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[J]}2==y?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&3)<<4],q+="=="):4==y&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(r&15)<<2],q+="=");n.src="data:audio/x-"+d.slice(-3)+";base64,"+q;f(n)}};n.src=l;Qb(()=>{f(n)})})});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Rb&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Vb(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var f={antialias:!1,alpha:!1,Rf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Wb&&(e=Xb(a,f)))var l=Yb[e].ue}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&Zb(e),Sb.forEach(n=>n()),jb());return l}
function Ub(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}
var ib={},Tb,M=12288,$b=!1,ac=0,bc=0,cc=0,N={alpha:!1,depth:!1,stencil:!1,antialias:!1},dc={},ec,P,fc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},gc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},hc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},ic=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},jc=1,kc=[],Q=[],lc=[],mc=[],nc=[],S=[],oc=[],Yb=[],pc=[],qc={},rc=4,sc=0,tc=a=>{for(var b=jc++,c=a.length;c<b;c++)a[c]=null;return b},uc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=P[c](),g=f&&tc(d);f?(f.name=g,d[g]=f):T||=1282;t[b+4*e>>2]=g}},Xb=(a,b)=>{a.de||(a.de=a.getContext,a.getContext=function(d,e){e=a.de(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?vc(c,b):0},vc=(a,b)=>
{var c=tc(Yb),d={handle:c,attributes:b,version:b.Rf,ue:a};a.canvas&&(a.canvas.Ie=d);Yb[c]=d;if("undefined"==typeof b.ng||b.ng)if((a=d)||(a=wc),!a.xg){a.xg=!0;a=a.ue;a.yh=a.getExtension("WEBGL_multi_draw");a.qg=a.getExtension("EXT_polygon_offset_clamp");a.pg=a.getExtension("EXT_clip_control");a.Lg=a.getExtension("WEBGL_polygon_mode");fc(a);gc(a);hc(a);a.qe=a.getExtension("EXT_disjoint_timer_query");for(var e of ic(a))e.includes("lose_context")||e.includes("debug")||a.getExtension(e)}return c},Zb=a=>
{wc=Yb[a];h.ctx=P=wc?.ue},Wb={},T,wc,xc=a=>{var b=Ra(a)+1,c=V(b);c&&D(a,p,c,b);return c},Oc=(a,b,c,d,e)=>{function f(){return g<yc?(Nb(),!1):!0}zc=a;Ac=d;var g=yc;Bc=!1;Cc=function(){if(!ha)if(0<Dc.length){var l=Dc.shift();l.ph(l.Ng);if(Ec){var n=Ec,q=0==n%1?n-1:Math.floor(n);Ec=l.$g?q:(8*n+(q+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=Ec??0,q=Fc.fh??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(Cc,0)}else if(f())if(Gc=
Gc+1|0,1==Hc&&1<Ic&&0!=Gc%Ic)Jc();else{0==Hc&&(Kc=performance.now());a:if(!ha){for(l of Lc)if(!1===l())break a;Ob(a);for(n of Mc)n()}f()&&Jc()}};e||(0<b?Nc(0,1E3/b):Nc(1,1),Jc());if(c)throw"unwind";},Bc=!1,Jc=null,yc=0,zc=null,Ac=0,Hc=0,Ic=0,Gc=0,Dc=[],Lc=[],Mc=[];function Pc(){Jc=null;yc++}var Qc=0;function Rc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Qc)Qc=b+1E3/60;else for(;b+2>=Qc;)Qc+=1E3/60;setTimeout(a,Math.max(Qc-b,0))}}
var Fc={},Cc,Ec,Kc,Sc,Nc=(a,b)=>{Hc=a;Ic=b;if(zc)if(Bc||=!0,0==a)Jc=function(){setTimeout(Cc,Math.max(0,Kc+b-performance.now())|0)};else if(1==a)Jc=function(){Rc(Cc)};else{if(!Sc)if(globalThis.setImmediate)Sc=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sc=d=>{c.push(d);postMessage("setimmediate","*")}}Jc=function(){Sc(Cc)}}},Tc=[],Uc=(a,b)=>{Tc.length=0;for(var c;c=p[a++];){var d=105!=c;d&=
112!=c;b+=d&&b%8?4:0;Tc.push(112==c?u[b>>2]:106==c?qa[b>>3]:105==c?t[b>>2]:w[b>>3]);b+=d?8:4}return Tc};function Vc(a){var b=W.ae[a];b.target.removeEventListener(b.Xd,b.Nf,b.fe);W.ae.splice(a,1)}function Wc(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of W.we)if(e.wf==a&&d(e.Gf,c))return;W.we.push({wf:a,Uf:b,Gf:c});W.we.sort((f,g)=>f.Uf-g.Uf)}function Xc(a){W.we=W.we.filter(b=>b.wf!=a)}
function Yc(){return navigator.userActivation?navigator.userActivation.isActive:W.kf&&W.fg.Oe}function Zc(){if(Yc()){var a=W.we;W.we=[];for(var b of a)b.wf(...b.Gf)}}function X(a){if(!a.target)return-4;if(a.Zd)a.Nf=function(c){++W.kf;W.fg=a;Zc();a.je(c);Zc();--W.kf},a.target.addEventListener(a.Xd,a.Nf,a.fe),W.ae.push(a);else for(var b=0;b<W.ae.length;++b)W.ae[b].target==a.target&&W.ae[b].Xd==a.Xd&&Vc(b--);return 0}
function $c(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var W={Og:0,hf:0,pf:0,Ze:0,Bf:0,yf:0,ff:0,dh:0,Ah:0,bh:0,gf:0,tf:0,Af:0,xf:0,Fh(){for(;W.ae.length;)Vc(W.ae.length-1);W.we=[]},kf:0,we:[],ae:[],Ig:(a,b)=>{for(var c=0;c<W.ae.length;++c)W.ae[c].target!=a||b&&b!=W.ae[c].Xd||Vc(c--)},Gh(a){let b=!1;for(let c=0;c<W.ae.length;++c){const d=W.ae[c];d.target===a.target&&d.ee===a.ee&&d.Zd===a.Zd&&d.ge===a.ge&&(Vc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},ad=[0,document,window],Y=a=>
{a=2<a?a?C(p,a):"":a;return ad[a]||document.querySelector(a)},cd=a=>{var b=Ra(a)+1,c=bd(b);D(a,p,c,b);return c},fd=a=>{var b=dd(),c=bd(8),d=c+4;a=cd(a.id);if(a=Y(a))t[c>>2]=a.width,t[d>>2]=a.height;c=[t[c>>2],t[d>>2]];ed(b);return c},gd=(a,b,c)=>{a=Y(a);if(!a)return-4;a.width=b;a.height=c;return 0},hd=(a,b,c)=>{if(a.Zg){var d=dd();a=cd(a.id);gd(a,b,c);ed(d)}else a.width=b,a.height=c},jd={},kd=a=>{function b(){Pb()||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),hd(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=q,a.style.paddingRight=r,a.style.paddingTop=y,a.style.paddingBottom=B,a.style.marginLeft=J,a.style.marginRight=G,a.style.marginTop=R,a.style.marginBottom=I,document.body.style.margin=U,document.documentElement.style.overflow=Gb,document.body.scroll=O,a.style.xe=Vd,a.Ie&&a.Ie.ue.viewport(0,0,d,e),jd.Pe&&z(jd.Pe)(37,0,jd.If))}
var c=fd(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,q=a.style.paddingLeft,r=a.style.paddingRight,y=a.style.paddingTop,B=a.style.paddingBottom,J=a.style.marginLeft,G=a.style.marginRight,R=a.style.marginTop,I=a.style.marginBottom,U=document.body.style.margin,Gb=document.documentElement.style.overflow,O=document.body.scroll,Vd=a.style.xe;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},ld=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},md=a=>0>ad.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},nd=(a,b)=>{if(0!=b.vf||0!=b.cf){kd(a);var c=b.Jg?innerWidth:screen.width,d=b.Jg?innerHeight:screen.height,e=md(a),f=e.width;e=e.height;var g=fd(a),l=g[0];g=g[1];3==b.vf?(ld(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.vf&&(c*g<l*d?(f=g*c/l,ld(a,(d-f)/2,0),d=f):(f=l*d/g,ld(a,0,(c-f)/2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let q;(q=document.body.style).backgroundColor||(q.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.sg&&(a.style.xe="optimizeSpeed",a.style.xe="-moz-crisp-edges",a.style.xe="-o-crisp-edges",a.style.xe="-webkit-optimize-contrast",a.style.xe="optimize-contrast",a.style.xe="crisp-edges",a.style.xe="pixelated");n=2==b.cf?devicePixelRatio:1;0!=b.cf&&(c=c*n|0,d=d*n|0,hd(a,c,d),a.Ie&&a.Ie.ue.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return W.fullscreenEnabled()?-3:-1;jd=b;b.Pe&&z(b.Pe)(37,0,b.If);return 0},od=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},pd=(a,b)=>{w[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)w[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)w[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)m[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
m[a+1104]=b.connected;t[a+1108>>2]=b.index;t[a+8>>2]=b.axes.length;t[a+12>>2]=b.buttons.length;D(b.id,p,a+1112,64);D(b.mapping,p,a+1176,64)},qd=[],rd=(a,b,c,d,e,f,g,l)=>{b=Q[b];if(a=P[a](b,c))d=l&&D(a.name,p,l,d),e&&(t[e>>2]=d),f&&(t[f>>2]=a.size),g&&(t[g>>2]=a.type)},sd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(T||=1280);return;case 36345:d=0;break;case 34466:var e=P.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=P.getParameter(a),typeof e){case "number":d=
e;break;case "boolean":d=e?1:0;break;case "string":T||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:T||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:t[b+4*a>>2]=e[a];break;case 2:v[b+4*a>>2]=e[a];break;case 4:m[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){T||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);
return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;u[b>>2]=c;u[b+4>>2]=(c-u[b>>2])/4294967296;break;case 0:t[b>>2]=d;break;case 2:v[b>>2]=d;break;case 4:m[b]=d?1:0}}else T||=1281},td=(a,b,c)=>{if(c){a=P.qe.getQueryObjectEXT(pc[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d;u[c+4>>2]=(d-u[c>>2])/4294967296}else T||=1281},ud=(a,b,c)=>{if(c){a=P.qe.getQueryObjectEXT(pc[a],
b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d}else T||=1281},vd=()=>{var a=ic(P);return a=a.concat(a.map(b=>"GL_"+b))},wd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),xd=a=>{var b=a.Ne,c=a.Yf,d;if(!b){a.Ne=b={};a.Xf={};var e=P.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=P.getActiveUniform(a,d);var g=f.name;f=f.size;var l=wd(g);l=0<l?g.slice(0,l):g;var n=a.zf;a.zf+=f;c[l]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Xf[n++]=l}}},Z=a=>{var b=P.gg;if(b){var c=b.Ne[a];"number"==typeof c&&(b.Ne[a]=c=P.getUniformLocation(b,
b.Xf[a]+(0<c?`[${c}]`:"")));return c}T||=1282},yd=(a,b,c,d)=>{if(c)if(a=Q[a],xd(a),a=P.getUniform(a,Z(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:v[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b]}else T||=1281},zd=(a,b,c,d)=>{if(c)if(a=P.getVertexAttrib(a,b),34975==b)t[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:t[c>>2]=a;break;case 2:v[c>>2]=a;break;case 5:t[c>>2]=Math.fround(a)}else for(b=
0;b<a.length;b++)switch(d){case 0:t[c+4*b>>2]=a[b];break;case 2:v[c+4*b>>2]=a[b];break;case 5:t[c+4*b>>2]=Math.fround(a[b])}else T||=1281},Ad=(a,b,c,d,e)=>{a-=5120;a=1==a?p:4==a?t:6==a?v:5==a||28922==a?u:pa;b=d*((sc||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+rc-1&-rc);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Bd=[],Cd=[],Dd=(a,b)=>{if(!W.fullscreenEnabled())return-1;a=Y(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?
Yc()?nd(a,b):b.kg?(Wc(nd,1,[a,b]),1):-2:-3:-4},Ed=()=>{try{if(navigator.getGamepads)return(W.Ve=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Fd=(a,b)=>{var c={target:Y(2),Xd:"beforeunload",ee:28,ge:a,Zd:b,je:d=>{var e=z(b)(28,0,a);e&&=e?C(p,e):"";if(e)return d.preventDefault(),d.returnValue=e},fe:!0};return X(c)},Gd=(a,b,c,d,e,f)=>{W.ff||(W.ff=V(256));a={target:Y(a),Xd:f,ee:e,ge:b,Zd:d,je:g=>{var l=g.target.id?g.target.id:"",n=W.ff;D($c(g.target),p,n+0,128);D(l,p,n+
128,128);z(d)(e,n,b)&&g.preventDefault()},fe:c};return X(a)},Hd=(a,b,c,d,e)=>{W.gf||(W.gf=V(276));return X({target:a,Xd:e,ee:19,ge:b,Zd:d,je:f=>{var g=W.gf,l=Pb(),n=!!l;m[g]=n;m[g+1]=W.fullscreenEnabled();var q=n?l:W.Hg,r=q?.id||"";D($c(q),p,g+2,128);D(r,p,g+130,128);t[g+260>>2]=q?q.clientWidth:0;t[g+264>>2]=q?q.clientHeight:0;t[g+268>>2]=screen.width;t[g+272>>2]=screen.height;n&&(W.Hg=l);z(d)(19,g,b)&&f.preventDefault()},fe:c})},Id=(a,b,c,d,e)=>{W.hf||(W.hf=V(1240));b={target:Y(2),Oe:!0,Xd:e,ee:d,
ge:a,Zd:c,je:f=>{var g=W.hf;pd(g,f.gamepad);z(c)(d,g,a)&&f.preventDefault()},fe:b};return X(b)},Jd=(a,b,c,d,e,f)=>{W.pf||(W.pf=V(160));a={target:Y(a),Xd:f,ee:e,ge:b,Zd:d,je:g=>{var l=W.pf;w[l>>3]=g.timeStamp;var n=l>>2;t[n+2]=g.location;m[l+12]=g.ctrlKey;m[l+13]=g.shiftKey;m[l+14]=g.altKey;m[l+15]=g.metaKey;m[l+16]=g.repeat;t[n+5]=g.charCode;t[n+6]=g.keyCode;t[n+7]=g.which;D(g.key||"",p,l+32,32);D(g.code||"",p,l+64,32);D(g.char||"",p,l+96,32);D(g.locale||"",p,l+128,32);z(d)(e,l,b)&&g.preventDefault()},
fe:c};return X(a)},Kd=(a,b,c)=>{w[a>>3]=b.timeStamp;var d=a>>2;t[d+2]=b.screenX;t[d+3]=b.screenY;t[d+4]=b.clientX;t[d+5]=b.clientY;m[a+24]=b.ctrlKey;m[a+25]=b.shiftKey;m[a+26]=b.altKey;m[a+27]=b.metaKey;oa[2*d+14]=b.button;oa[2*d+15]=b.buttons;t[d+8]=b.movementX;t[d+9]=b.movementY;a=md(c);t[d+10]=b.clientX-(a.left|0);t[d+11]=b.clientY-(a.top|0)},Ld=(a,b,c,d,e,f)=>{W.Ze||(W.Ze=V(64));a=Y(a);return X({target:a,Oe:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Xd:f,ee:e,ge:b,Zd:d,je:g=>{Kd(W.Ze,g,
a);z(d)(e,W.Ze,b)&&g.preventDefault()},fe:c})},Md=(a,b,c,d)=>{W.tf||(W.tf=V(257));return X({target:a,Xd:"pointerlockchange",ee:20,ge:b,Zd:d,je:e=>{var f=W.tf,g=document.pointerLockElement;m[f]=!!g;var l=g?.id||"";D($c(g),p,f+1,128);D(l,p,f+129,128);z(d)(20,f,b)&&e.preventDefault()},fe:c})},Nd=(a,b,c,d)=>{W.yf||(W.yf=V(36));a=Y(a);return X({target:a,Xd:"resize",ee:10,ge:b,Zd:d,je:e=>{if(e.target==a){var f=document.body;if(f){var g=W.yf;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+
12>>2]=innerWidth;t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=pageYOffset|0;z(d)(10,g,b)&&e.preventDefault()}}},fe:c})},Od=(a,b,c,d,e,f)=>{W.xf||(W.xf=V(1552));a=Y(a);return X({target:a,Oe:"touchstart"==f||"touchend"==f,Xd:f,ee:e,ge:b,Zd:d,je:g=>{var l={},n=g.touches;for(var q of n)q.Qf=q.Tf=0,l[q.identifier]=q;for(var r of g.changedTouches)r.Qf=1,l[r.identifier]=r;for(var y of g.targetTouches)l[y.identifier].Tf=1;n=W.xf;w[n>>3]=g.timeStamp;
m[n+12]=g.ctrlKey;m[n+13]=g.shiftKey;m[n+14]=g.altKey;m[n+15]=g.metaKey;q=n+16;r=md(a);y=0;for(let B of Object.values(l))if(l=q>>2,t[l]=B.identifier,t[l+1]=B.screenX,t[l+2]=B.screenY,t[l+3]=B.clientX,t[l+4]=B.clientY,t[l+5]=B.pageX,t[l+6]=B.pageY,m[q+28]=B.Qf,m[q+29]=B.Tf,t[l+8]=B.clientX-(r.left|0),t[l+9]=B.clientY-(r.top|0),q+=48,31<++y)break;t[n+8>>2]=y;z(d)(e,n,b)&&g.preventDefault()},fe:c})},Pd=(a,b,c)=>{var d=ad[1];W.Af||(W.Af=V(8));return X({target:d,Xd:"visibilitychange",ee:21,ge:a,Zd:c,je:e=>
{var f=W.Af,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);m[f]=document.hidden;t[f+4>>2]=g;z(c)(21,f,a)&&e.preventDefault()},fe:b})},Qd=(a,b,c,d)=>{W.Bf||(W.Bf=V(96));return X({target:a,Oe:!0,Xd:"wheel",ee:9,ge:b,Zd:d,je:e=>{var f=W.Bf;Kd(f,e,a);w[f+64>>3]=e.deltaX;w[f+72>>3]=e.deltaY;w[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;z(d)(9,f,b)&&e.preventDefault()},fe:c})},Rd={},Td=()=>{if(!Sd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Rd)void 0===Rd[b]?delete a[b]:a[b]=Rd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Sd=c}return Sd},Sd,Ud=a=>{for(var b of["keydown","mousedown","touchstart"])for(var c of[document,document.getElementById("canvas")])c?.addEventListener(b,()=>{"suspended"===a.state&&a.resume()},{once:!0})},Wd=(a,b=[])=>{z(a)(...b)},Xd=(a,b,c,d)=>{var e={string:q=>{var r=0;null!==q&&void 0!==q&&0!==q&&(r=cd(q));return r},
array:q=>{var r=bd(q.length);m.set(q,r);return r}};a=h["_"+a];var f=[],g=0;if(d)for(var l=0;l<d.length;l++){var n=e[c[l]];n?(0===g&&(g=dd()),f[l]=n(d[l])):f[l]=d[l]}c=a(...f);return c=function(q){0!==g&&ed(g);return"string"===b?q?C(p,q):"":"boolean"===b?!!q:q}(c)};A.ah=(a,b,c,d,e,f,g,l,n,q)=>{mb(a,b,c,d,e,l,n,q).then(f).catch(g)};A.Bh=mb;A.se=Array(4096);A.Vd(E,{},"/");L("/tmp");L("/home");L("/home/web_user");
(function(){L("/dev");Va(A.Be(1,3),{read:()=>0,write:(d,e,f,g)=>g,be:()=>0});Ab("/dev/null",A.Be(1,3));Ua(A.Be(5,0),Xa);Ua(A.Be(6,0),Ya);Ab("/dev/tty",A.Be(5,0));Ab("/dev/tty1",A.Be(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ma(a),b=a.byteLength);return a[--b]};A.ve("/dev","random",c);A.ve("/dev","urandom",c);L("/dev/shm");L("/dev/shm/tmp")})();
(function(){L("/proc");var a=L("/proc/self");L("/proc/self/fd");A.Vd({Vd(){var b=A.createNode(a,"fd",16895,73);b.Rd={be:E.Rd.be};b.Qd={Ae(c,d){c=+d;var e=K(c);c={parent:null,Vd:{Sf:"fake"},Qd:{ye:()=>e.path},id:c+1};return c.parent=c},Me(){return Array.from(A.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();A.rg={MEMFS:E};h.requestAnimationFrame=Rc;h.pauseMainLoop=Pc;
h.resumeMainLoop=function(){yc++;var a=Hc,b=Ic,c=zc;zc=null;Oc(c,0,!1,Ac,!0);Nc(a,b);Jc()};h.preMainLoop&&Lc.push(h.preMainLoop);h.postMainLoop&&Mc.push(h.postMainLoop);for(let a=0;32>a;++a)qd.push(Array(a));for(var Yd=new Float32Array(288),Zd=0;288>=Zd;++Zd)Bd[Zd]=Yd.subarray(0,Zd);var $d=new Int32Array(288);for(Zd=0;288>=Zd;++Zd)Cd[Zd]=$d.subarray(0,Zd);h.noExitRuntime&&(Aa=h.noExitRuntime);h.preloadPlugins&&(hb=h.preloadPlugins);h.print&&(ea=h.print);h.printErr&&(k=h.printErr);
h.wasmBinary&&(fa=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.callMain=ae;h.addRunDependency=gb;h.removeRunDependency=fb;h.ccall=Xd;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>Xd(a,b,c,f,d)};h.createContext=Vb;h.FS_preloadFile=mb;h.FS_unlink=(...a)=>A.Fe(...a);
h.FS_createPath=(...a)=>Db(...a);h.FS_createDevice=(...a)=>A.ve(...a);h.FS=A;h.FS_createDataFile=(...a)=>lb(...a);h.FS_createLazyFile=(...a)=>Hb(...a);
var be={392984:a=>{a=(a?C(p,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return 1===a.length?a.charCodeAt(0):-1},393199:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,393346:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,393580:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture=
{}:b.audio={};b.Ud||("undefined"!==typeof AudioContext?b.Ud=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Ud=new webkitAudioContext),b.Ud&&"undefined"===typeof navigator.userActivation&&Ud(b.Ud));return void 0===b.Ud?-1:0},394132:()=>h.SDL2.Ud.sampleRate,394200:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.capture.ne&&(clearInterval(g.capture.ne),g.capture.ne=void 0,g.capture.Ee=void 0);g.capture.rf=g.Ud.createMediaStreamSource(l);g.capture.le=g.Ud.createScriptProcessor(b,a,1);
g.capture.le.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.df=n.inputBuffer,Wd(c,[d]))};g.capture.rf.connect(g.capture.le);g.capture.le.connect(g.Ud.destination);g.capture.stream=l}var g=h.SDL2;g.capture.Ee=g.Ud.createBuffer(a,b,g.Ud.sampleRate);g.capture.Ee.getChannelData(0).fill(0);g.capture.ne=setInterval(function(){g.capture.df=g.capture.Ee;Wd(c,[d])},b/g.Ud.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?
navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},395893:(a,b,c,d)=>{var e=h.SDL2;e.audio.le=e.Ud.createScriptProcessor(b,0,a);e.audio.le.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.ne&&(clearInterval(e.audio.ne),e.audio.ne=void 0,e.audio.Ee=void 0),e.audio.Re=f.outputBuffer,Wd(c,[d]))};e.audio.le.connect(e.Ud.destination);"suspended"===e.Ud.state&&(e.audio.Ee=
e.Ud.createBuffer(a,b,e.Ud.sampleRate),e.audio.Ee.getChannelData(0).fill(0),e.audio.ne=setInterval(function(){"undefined"!==typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.Ud.resume();e.audio.Re=e.audio.Ee;Wd(c,[d]);e.audio.Re=void 0},b/e.Ud.sampleRate*1E3))},397068:(a,b)=>{for(var c=h.SDL2,d=c.capture.df.numberOfChannels,e=0;e<d;++e){var f=c.capture.df.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+
b+" samples!";if(1==d)for(var g=0;g<b;++g)Ba(a+4*g,f[g]);else for(g=0;g<b;++g)Ba(a+4*(g*d+e),f[g])}},397673:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=c.audio.Re.numberOfChannels,e=0;e<d;++e){var f=c.audio.Re.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=v[a+(g*d+e)]}},398162:a=>{var b=h.SDL2;if(a){void 0!==b.capture.ne&&clearInterval(b.capture.ne);if(void 0!==b.capture.stream){a=
b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.le&&(b.capture.le.onaudioprocess=function(){},b.capture.le.disconnect());void 0!==b.capture.rf&&b.capture.rf.disconnect();b.capture=void 0}else void 0!=b.audio.le&&b.audio.le.disconnect(),void 0!==b.audio.ne&&clearInterval(b.audio.ne),b.audio=void 0;void 0!==b.Ud&&void 0===b.audio&&void 0===b.capture&&(b.Ud.close(),b.Ud=void 0)},399168:()=>window.innerWidth,399198:()=>window.innerHeight,
399229:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.eg!==h.canvas&&(d.Qe=Vb(h.canvas,!1,!0),d.eg=h.canvas);if(d.w!==a||d.h!==b||d.wg!==d.Qe)d.image=d.Qe.createImageData(a,b),d.w=a,d.h=b,d.wg=d.Qe;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=t[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.ig!==a&&(d.hg=new Int32Array(a.buffer),d.jg=new Uint8Array(a.buffer),d.ig=a),a=d.hg,c=a.length,a.set(t.subarray(b,
b+c)),a=d.jg,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Qe.putImageData(d.image,0,0)},400695:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var q=t[e];
b[l]=q&255;b[l+1]=q>>8&255;b[l+2]=q>>16&255;b[l+3]=q>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(t.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=V(c.length+1);D(c,p,d,c.length+1);return d},401683:a=>{h.canvas&&(h.canvas.style.cursor=a?C(p,a):"")},401766:()=>{h.canvas&&(h.canvas.style.cursor="none")}},V,ce,de,ed,bd,dd,na,Da,ee={sc:(a,b)=>z(a)(b),I:function(a,b,c){Ea=c;try{var d=K(a);switch(b){case 0:var e=
Fa();if(0>e)break;for(;A.streams[e];)e++;return wb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Fa(),d.flags|=e,0;case 12:return e=Fa(),oa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof A||"ErrnoError"!==f.name)throw f;return-f.Wd}},ta:function(a,b,c){Ea=c;try{var d=K(a);switch(b){case 21509:return d.Td?0:-59;case 21505:if(!d.Td)return-59;if(d.Td.te.zg){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Fa();
t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;32>f;f++)m[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Td?0:-59;case 21506:case 21507:case 21508:if(!d.Td)return-59;if(d.Td.te.Ag)for(e=Fa(),a=[],f=0;32>f;f++)a.push(m[e+f+17]);return 0;case 21519:if(!d.Td)return-59;e=Fa();return t[e>>2]=0;case 21520:return d.Td?-28:-59;case 21537:case 21531:return e=Fa(),A.mf(d,b,e);case 21523:if(!d.Td)return-59;d.Td.te.Bg&&(f=[24,80],e=Fa(),oa[e>>1]=f[0],oa[e+2>>1]=f[1]);
return 0;case 21524:return d.Td?0:-59;case 21515:return d.Td?0:-59;default:return-28}}catch(g){if("undefined"==typeof A||"ErrnoError"!==g.name)throw g;return-g.Wd}},Ed:function(a,b,c){try{return b=b?C(p,b):"",b=Ib(a,b),L(b,c),0}catch(d){if("undefined"==typeof A||"ErrnoError"!==d.name)throw d;return-d.Wd}},Cb:function(a,b,c,d){Ea=d;try{b=b?C(p,b):"";b=Ib(a,b);var e=d?Fa():0;return A.open(b,c,e).fd}catch(f){if("undefined"==typeof A||"ErrnoError"!==f.name)throw f;return-f.Wd}},Nb:function(a,b,c,d){try{return b=
b?C(p,b):"",d=d?C(p,d):"",b=Ib(a,b),d=Ib(c,d),A.He(b,d),0}catch(e){if("undefined"==typeof A||"ErrnoError"!==e.name)throw e;return-e.Wd}},Yb:function(a){try{return a=a?C(p,a):"",A.De(a),0}catch(b){if("undefined"==typeof A||"ErrnoError"!==b.name)throw b;return-b.Wd}},Da:function(a,b){try{a=a?C(p,a):"";var c=A.stat(a);u[b>>2]=c.lg;u[b+4>>2]=c.mode;u[b+8>>2]=c.Eg;u[b+12>>2]=c.uid;u[b+16>>2]=c.vg;u[b+20>>2]=c.Le;qa[b+24>>3]=BigInt(c.size);t[b+32>>2]=4096;t[b+36>>2]=c.Hf;var d=c.pe.getTime(),e=c.ce.getTime(),
f=c.$d.getTime();qa[b+40>>3]=BigInt(Math.floor(d/1E3));u[b+48>>2]=d%1E3*1E6;qa[b+56>>3]=BigInt(Math.floor(e/1E3));u[b+64>>2]=e%1E3*1E6;qa[b+72>>3]=BigInt(Math.floor(f/1E3));u[b+80>>2]=f%1E3*1E6;qa[b+88>>3]=BigInt(c.yg);return 0}catch(g){if("undefined"==typeof A||"ErrnoError"!==g.name)throw g;return-g.Wd}},hc:function(a,b,c){try{b=b?C(p,b):"";b=Ib(a,b);if(c)if(512===c)A.De(b);else return-28;else A.Fe(b);return 0}catch(d){if("undefined"==typeof A||"ErrnoError"!==d.name)throw d;return-d.Wd}},Zc:()=>
x(""),Oc:()=>{Aa=!1;Jb=0},Bb:a=>a?-52:0,Ea:(a,b)=>{Kb[a]&&(clearTimeout(Kb[a].id),delete Kb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Kb[a];Ob(()=>de(a,performance.now()))},b);Kb[a]={id:c,Ih:b};return 0},ka:a=>{if(12448==a)return M=12288,1;M=12300;return 0},wa:(a,b,c,d,e)=>{if(62E3!=a)M=12296,c=0;else{if(b)for(;;){a=t[b>>2];if(12321==a)N.alpha=0<t[b+4>>2];else if(12325==a)N.depth=0<t[b+4>>2];else if(12326==a)N.stencil=0<t[b+4>>2];else if(12337==a)a=t[b+4>>2],N.antialias=0<a;else if(12338==a)a=
t[b+4>>2],N.antialias=1==a;else if(12544==a)N.th=12547!=t[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(t[e>>2]=1),c&&0<d&&(u[c>>2]=62002),M=12288,c=1):(M=12300,c=0)}return c},ua:(a,b,c,d)=>{if(62E3!=a)return M=12296,0;for(a=1;;){b=t[d>>2];if(12440==b)a=t[d+4>>2];else if(12344==b)break;else return M=12292,0;d+=8}if(2!=a)return M=12293,0;N.Rf=a-1;N.wh=0;ec=Xb(h.canvas,N);if(0!=ec)return M=12288,Zb(ec),Sb.forEach(e=>e()),Zb(null),62004;M=12297;return 0},ra:(a,b)=>{if(62E3!=a)return M=12296,0;if(62002!=
b)return M=12293,0;M=12288;return 62006},sa:(a,b)=>{if(62E3!=a)return M=12296,0;if(62004!=b)return M=12294,0;a=ec;wc===Yb[a]&&(wc=null);"object"==typeof W&&W.Ig(Yb[a].ue.canvas);Yb[a]?.ue.canvas&&(Yb[a].ue.canvas.Ie=void 0);Yb[a]=null;M=12288;ac==b&&(ac=0);return 1},qa:(a,b)=>{if(62E3!=a)return M=12296,0;if(62006!=b)return M=12301,1;bc==b&&(bc=0);cc==b&&(cc=0);M=12288;return 1},va:(a,b,c,d)=>{if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;if(!d)return M=12300,0;M=12288;switch(c){case 12320:return t[d>>
2]=N.alpha?32:24,1;case 12321:return t[d>>2]=N.alpha?8:0,1;case 12322:return t[d>>2]=8,1;case 12323:return t[d>>2]=8,1;case 12324:return t[d>>2]=8,1;case 12325:return t[d>>2]=N.depth?24:0,1;case 12326:return t[d>>2]=N.stencil?8:0,1;case 12327:return t[d>>2]=12344,1;case 12328:return t[d>>2]=62002,1;case 12329:return t[d>>2]=0,1;case 12330:return t[d>>2]=4096,1;case 12331:return t[d>>2]=16777216,1;case 12332:return t[d>>2]=4096,1;case 12333:return t[d>>2]=0,1;case 12334:return t[d>>2]=0,1;case 12335:return t[d>>
2]=12344,1;case 12337:return t[d>>2]=N.antialias?4:0,1;case 12338:return t[d>>2]=N.antialias?1:0,1;case 12339:return t[d>>2]=4,1;case 12340:return t[d>>2]=12344,1;case 12341:case 12342:case 12343:return t[d>>2]=-1,1;case 12345:case 12346:return t[d>>2]=0,1;case 12347:return t[d>>2]=0,1;case 12348:return t[d>>2]=1;case 12349:case 12350:return t[d>>2]=0,1;case 12351:return t[d>>2]=12430,1;case 12352:return t[d>>2]=4,1;case 12354:return t[d>>2]=0,1;default:return M=12292,0}},H:a=>{M=12288;return 0!=
a&&1!=a?0:62E3},ha:()=>M,ya:(a,b,c)=>{if(62E3!=a)return M=12296,0;b&&(t[b>>2]=1);c&&(t[c>>2]=4);$b=!0;M=12288;return 1},pa:(a,b,c,d)=>{if(62E3!=a)return M=12296,0;if(0!=d&&62004!=d)return M=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return M=12301,0;Zb(d?ec:null);ac=d;cc=b;bc=c;M=12288;return 1},ja:(a,b)=>{if(62E3!=a)return M=12296,0;M=12288;if(dc[b])return dc[b];switch(b){case 12371:a=xc("Emscripten");break;case 12372:a=xc("1.4 Emscripten EGL");break;case 12373:a=xc("");break;case 12429:a=xc("OpenGL_ES");
break;default:return M=12300,0}return dc[b]=a},oa:()=>{if($b)if(P)if(P.isContextLost())M=12302;else return M=12288,1;else M=12290;else M=12289;return 0},na:(a,b)=>{if(62E3!=a)return M=12296,0;0==b?Nc(0,0):Nc(1,b);M=12288;return 1},xa:a=>{if(62E3!=a)return M=12296,0;cc=bc=ac=0;$b=!1;M=12288;return 1},la:()=>{M=12288;return 1},ma:()=>{M=12288;return 1},Ma:(a,b,c)=>{b=Uc(b,c);return be[a](...b)},a:(a,b,c)=>{b=Uc(b,c);return be[a](...b)},fa:(a,b,c)=>{b=Uc(b,c);return be[a](...b)},qb:()=>{Pc();zc=null},
za:()=>Date.now(),aa:()=>{if(!W.fullscreenEnabled())return-1;Xc(nd);var a=ad[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ea:()=>{Xc(od);if(!document.exitPointerLock)return-1;document.exitPointerLock();return 0},fb:a=>{Aa=!1;Jb=0;ia=a;Mb(a)},d:()=>devicePixelRatio,b:(a,b,c)=>{a=Y(a);if(!a)return-4;a=md(a);w[b>>3]=a.width;w[c>>3]=a.height;return 0},Aa:(a,b)=>{if(0>a||a>=W.Ve.length)return-5;
if(!W.Ve[a])return-7;pd(b,W.Ve[a]);return 0},g:()=>performance.now(),Ba:()=>W.Ve.length,ga:(a,b)=>{t[a>>2]=screen.width;t[b>>2]=screen.height},Cd:a=>P.activeTexture(a),Bd:(a,b)=>{P.attachShader(Q[a],S[b])},Y:(a,b)=>{P.qe.beginQueryEXT(a,pc[b])},Ad:(a,b,c)=>{P.bindAttribLocation(Q[a],b,c?C(p,c):"")},zd:(a,b)=>{P.bindBuffer(a,kc[b])},yd:(a,b)=>{P.bindFramebuffer(a,lc[b])},xd:(a,b)=>{P.bindRenderbuffer(a,mc[b])},wd:(a,b)=>{P.bindTexture(a,nc[b])},P:a=>{P.bindVertexArray(oc[a])},vd:(a,b,c,d)=>P.blendColor(a,
b,c,d),ud:a=>P.blendEquation(a),sd:(a,b)=>P.blendEquationSeparate(a,b),rd:(a,b)=>P.blendFunc(a,b),qd:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),pd:(a,b,c,d)=>{P.bufferData(a,c?p.subarray(c,c+b):b,d)},od:(a,b,c,d)=>{P.bufferSubData(a,b,p.subarray(d,d+c))},nd:a=>P.checkFramebufferStatus(a),md:a=>P.clear(a),ld:(a,b,c,d)=>P.clearColor(a,b,c,d),kd:a=>P.clearDepth(a),jd:a=>P.clearStencil(a),Ha:(a,b)=>{P.pg.clipControlEXT(a,b)},hd:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},gd:a=>{P.compileShader(S[a])},fd:(a,
b,c,d,e,f,g,l)=>{P.compressedTexImage2D(a,b,c,d,e,f,p.subarray(l,l+g))},ed:(a,b,c,d,e,f,g,l,n)=>{P.compressedTexSubImage2D(a,b,c,d,e,f,g,p.subarray(n,n+l))},dd:(a,b,c,d,e,f,g,l)=>P.copyTexImage2D(a,b,c,d,e,f,g,l),cd:(a,b,c,d,e,f,g,l)=>P.copyTexSubImage2D(a,b,c,d,e,f,g,l),bd:()=>{var a=tc(Q),b=P.createProgram();b.name=a;b.Ye=b.We=b.Xe=0;b.zf=1;Q[a]=b;return a},ad:a=>{var b=tc(S);S[b]=P.createShader(a);return b},$c:a=>P.cullFace(a),_c:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=kc[d];e&&(P.deleteBuffer(e),
e.name=0,kc[d]=null)}},Yc:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=lc[d];e&&(P.deleteFramebuffer(e),e.name=0,lc[d]=null)}},Xc:a=>{if(a){var b=Q[a];b?(P.deleteProgram(b),b.name=0,Q[a]=null):T||=1281}},_:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=pc[d];e&&(P.qe.deleteQueryEXT(e),pc[d]=null)}},Wc:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=mc[d];e&&(P.deleteRenderbuffer(e),e.name=0,mc[d]=null)}},Vc:a=>{if(a){var b=S[a];b?(P.deleteShader(b),S[a]=null):T||=1281}},Uc:(a,b)=>{for(var c=
0;c<a;c++){var d=t[b+4*c>>2],e=nc[d];e&&(P.deleteTexture(e),e.name=0,nc[d]=null)}},O:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];P.deleteVertexArray(oc[d]);oc[d]=null}},Tc:a=>P.depthFunc(a),Sc:a=>{P.depthMask(!!a)},Rc:(a,b)=>P.depthRange(a,b),Qc:(a,b)=>{P.detachShader(Q[a],S[b])},Pc:a=>P.disable(a),Nc:a=>{P.disableVertexAttribArray(a)},Mc:(a,b,c)=>{P.drawArrays(a,b,c)},K:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},L:(a,b)=>{for(var c=qd[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];P.drawBuffers(c)},Lc:(a,b,
c,d)=>{P.drawElements(a,b,c,d)},J:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},Kc:a=>P.enable(a),Jc:a=>{P.enableVertexAttribArray(a)},X:a=>{P.qe.endQueryEXT(a)},Ic:()=>P.finish(),Hc:()=>P.flush(),Gc:(a,b,c,d)=>{P.framebufferRenderbuffer(a,b,c,mc[d])},Fc:(a,b,c,d,e)=>{P.framebufferTexture2D(a,b,c,nc[d],e)},Ec:a=>P.frontFace(a),Cc:(a,b)=>{uc(a,b,"createBuffer",kc)},Ac:(a,b)=>{uc(a,b,"createFramebuffer",lc)},$:(a,b)=>{for(var c=0;c<a;c++){var d=P.qe.createQueryEXT();if(!d){for(T||=1282;c<a;)t[b+
4*c++>>2]=0;break}var e=tc(pc);d.name=e;pc[e]=d;t[b+4*c>>2]=e}},zc:(a,b)=>{uc(a,b,"createRenderbuffer",mc)},yc:(a,b)=>{uc(a,b,"createTexture",nc)},N:(a,b)=>{uc(a,b,"createVertexArray",oc)},Bc:a=>P.generateMipmap(a),xc:(a,b,c,d,e,f,g)=>rd("getActiveAttrib",a,b,c,d,e,f,g),wc:(a,b,c,d,e,f,g)=>rd("getActiveUniform",a,b,c,d,e,f,g),vc:(a,b,c,d)=>{a=P.getAttachedShaders(Q[a]);var e=a.length;e>b&&(e=b);t[c>>2]=e;for(b=0;b<e;++b)t[d+4*b>>2]=S.indexOf(a[b])},uc:(a,b)=>P.getAttribLocation(Q[a],b?C(p,b):""),
tc:(a,b)=>sd(a,b,4),rc:(a,b,c)=>{c?t[c>>2]=P.getBufferParameter(a,b):T||=1281},qc:()=>{var a=P.getError()||T;T=0;return a},pc:(a,b)=>sd(a,b,2),oc:(a,b,c,d)=>{a=P.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;t[d>>2]=a},nc:(a,b)=>sd(a,b,0),lc:(a,b,c,d)=>{a=P.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,p,d,b):0;c&&(t[c>>2]=b)},mc:(a,b,c)=>{if(c)if(a>=jc)T||=1281;else if(a=Q[a],35716==b)a=P.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.Ye){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ye=Math.max(a.Ye,P.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.Ye}else if(35722==b){if(!a.We)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.We=Math.max(a.We,P.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.We}else if(35381==b){if(!a.Xe)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.Xe=Math.max(a.Xe,P.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.Xe}else t[c>>
2]=P.getProgramParameter(a,b);else T||=1281},R:td,U:ud,Q:td,S:ud,V:(a,b,c)=>{c?t[c>>2]=P.qe.getQueryEXT(a,b):T||=1281},kc:(a,b,c)=>{c?t[c>>2]=P.getRenderbufferParameter(a,b):T||=1281},ic:(a,b,c,d)=>{a=P.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,p,d,b):0;c&&(t[c>>2]=b)},gc:(a,b,c,d)=>{a=P.getShaderPrecisionFormat(a,b);t[c>>2]=a.rangeMin;t[c+4>>2]=a.rangeMax;t[d>>2]=a.precision},fc:(a,b,c,d)=>{if(a=P.getShaderSource(S[a]))b=0<b&&d?D(a,p,d,b):0,c&&(t[c>>2]=b)},jc:(a,b,c)=>{c?
35716==b?(a=P.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(S[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=P.getShaderParameter(S[a],b):T||=1281},ec:a=>{var b=qc[a];if(!b){switch(a){case 7939:b=xc(vd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=P.getParameter(a))||(T||=1280);b=b?xc(b):0;break;case 7938:b=xc(`OpenGL ES 2.0 (${P.getParameter(7938)})`);break;case 35724:b=P.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=xc(b);break;default:T||=1280}qc[a]=b}return b},dc:(a,b,c)=>{c?v[c>>2]=P.getTexParameter(a,b):T||=1281},cc:(a,b,c)=>{c?t[c>>2]=P.getTexParameter(a,b):T||=1281},$b:(a,b)=>{b=b?C(p,b):"";if(a=Q[a]){xd(a);var c=a.Ne,d=0,e=b,f=wd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Yf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else T||=1281;return-1},bc:(a,b,c)=>{yd(a,b,c,2)},ac:(a,b,c)=>{yd(a,
b,c,0)},Xb:(a,b,c)=>{c?t[c>>2]=P.getVertexAttribOffset(a,b):T||=1281},_b:(a,b,c)=>{zd(a,b,c,2)},Zb:(a,b,c)=>{zd(a,b,c,5)},Wb:(a,b)=>P.hint(a,b),Vb:a=>(a=kc[a])?P.isBuffer(a):0,Ub:a=>P.isEnabled(a),Tb:a=>(a=lc[a])?P.isFramebuffer(a):0,Sb:a=>(a=Q[a])?P.isProgram(a):0,Z:a=>(a=pc[a])?P.qe.isQueryEXT(a):0,Rb:a=>(a=mc[a])?P.isRenderbuffer(a):0,Qb:a=>(a=S[a])?P.isShader(a):0,Pb:a=>(a=nc[a])?P.isTexture(a):0,M:a=>(a=oc[a])?P.isVertexArray(a):0,Ob:a=>P.lineWidth(a),Mb:a=>{a=Q[a];P.linkProgram(a);a.Ne=0;a.Yf=
{}},Lb:(a,b)=>{3317==a?rc=b:3314==a&&(sc=b);P.pixelStorei(a,b)},Ga:(a,b)=>{P.Lg.polygonModeWEBGL(a,b)},Kb:(a,b)=>P.polygonOffset(a,b),Ia:(a,b,c)=>{P.qg.polygonOffsetClampEXT(a,b,c)},W:(a,b)=>{P.qe.queryCounterEXT(pc[a],b)},Jb:(a,b,c,d,e,f,g)=>{(g=Ad(f,e,c,d,g))?P.readPixels(a,b,c,d,e,f,g):T||=1280},Ib:()=>{},Hb:(a,b,c,d)=>P.renderbufferStorage(a,b,c,d),Gb:(a,b)=>{P.sampleCoverage(a,!!b)},Fb:(a,b,c,d)=>P.scissor(a,b,c,d),Eb:()=>{T||=1280},Db:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=u[c+4*f>>
2])?C(p,g,d?u[d+4*f>>2]:void 0):"";e+=g}P.shaderSource(S[a],e)},Ab:(a,b,c)=>P.stencilFunc(a,b,c),zb:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),yb:a=>P.stencilMask(a),xb:(a,b)=>P.stencilMaskSeparate(a,b),wb:(a,b,c)=>P.stencilOp(a,b,c),vb:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),ub:(a,b,c,d,e,f,g,l,n)=>{n=n?Ad(l,g,d,e,n):null;P.texImage2D(a,b,c,d,e,f,g,l,n)},tb:(a,b,c)=>P.texParameterf(a,b,c),sb:(a,b,c)=>{P.texParameterf(a,b,v[c>>2])},rb:(a,b,c)=>P.texParameteri(a,b,c),pb:(a,b,c)=>{P.texParameteri(a,
b,t[c>>2])},ob:(a,b,c,d,e,f,g,l,n)=>{n=n?Ad(l,g,e,f,n):null;P.texSubImage2D(a,b,c,d,e,f,g,l,n)},nb:(a,b)=>{P.uniform1f(Z(a),b)},mb:(a,b,c)=>{if(288>=b)for(var d=Bd[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);P.uniform1fv(Z(a),d)},lb:(a,b)=>{P.uniform1i(Z(a),b)},kb:(a,b,c)=>{if(288>=b)for(var d=Cd[b],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);P.uniform1iv(Z(a),d)},jb:(a,b,c)=>{P.uniform2f(Z(a),b,c)},ib:(a,b,c)=>{if(144>=b){b*=2;for(var d=Bd[b],e=0;e<b;e+=2)d[e]=
v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);P.uniform2fv(Z(a),d)},hb:(a,b,c)=>{P.uniform2i(Z(a),b,c)},gb:(a,b,c)=>{if(144>=b){b*=2;for(var d=Cd[b],e=0;e<b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2]}else d=t.subarray(c>>2,c+8*b>>2);P.uniform2iv(Z(a),d)},eb:(a,b,c,d)=>{P.uniform3f(Z(a),b,c,d)},db:(a,b,c)=>{if(96>=b){b*=3;for(var d=Bd[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);P.uniform3fv(Z(a),d)},cb:(a,
b,c,d)=>{P.uniform3i(Z(a),b,c,d)},bb:(a,b,c)=>{if(96>=b){b*=3;for(var d=Cd[b],e=0;e<b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2]}else d=t.subarray(c>>2,c+12*b>>2);P.uniform3iv(Z(a),d)},ab:(a,b,c,d,e)=>{P.uniform4f(Z(a),b,c,d,e)},$a:(a,b,c)=>{if(72>=b){var d=Bd[4*b],e=v;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=v.subarray(c>>2,c+16*b>>2);P.uniform4fv(Z(a),d)},_a:(a,b,c,d,e)=>{P.uniform4i(Z(a),b,c,d,e)},Za:(a,b,c)=>
{if(72>=b){b*=4;for(var d=Cd[b],e=0;e<b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2]}else d=t.subarray(c>>2,c+16*b>>2);P.uniform4iv(Z(a),d)},Ya:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=Bd[b],f=0;f<b;f+=4)e[f]=v[d+4*f>>2],e[f+1]=v[d+(4*f+4)>>2],e[f+2]=v[d+(4*f+8)>>2],e[f+3]=v[d+(4*f+12)>>2]}else e=v.subarray(d>>2,d+16*b>>2);P.uniformMatrix2fv(Z(a),!!c,e)},Xa:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=Bd[b],f=0;f<b;f+=9)e[f]=v[d+4*f>>2],e[f+1]=v[d+(4*f+4)>>2],e[f+
2]=v[d+(4*f+8)>>2],e[f+3]=v[d+(4*f+12)>>2],e[f+4]=v[d+(4*f+16)>>2],e[f+5]=v[d+(4*f+20)>>2],e[f+6]=v[d+(4*f+24)>>2],e[f+7]=v[d+(4*f+28)>>2],e[f+8]=v[d+(4*f+32)>>2]}else e=v.subarray(d>>2,d+36*b>>2);P.uniformMatrix3fv(Z(a),!!c,e)},Wa:(a,b,c,d)=>{if(18>=b){var e=Bd[16*b],f=v;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];
e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=v.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(Z(a),!!c,e)},Va:a=>{a=Q[a];P.useProgram(a);P.gg=a},Ua:a=>{P.validateProgram(Q[a])},Ta:(a,b)=>P.vertexAttrib1f(a,b),Sa:(a,b)=>{P.vertexAttrib1f(a,v[b>>2])},Ra:(a,b,c)=>P.vertexAttrib2f(a,b,c),Qa:(a,b)=>{P.vertexAttrib2f(a,v[b>>2],v[b+4>>2])},Pa:(a,b,c,d)=>P.vertexAttrib3f(a,b,c,d),Oa:(a,b)=>{P.vertexAttrib3f(a,v[b>>2],v[b+4>>2],v[b+8>>2])},Na:(a,b,c,d,e)=>P.vertexAttrib4f(a,b,c,d,e),La:(a,b)=>{P.vertexAttrib4f(a,
v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},Dd:(a,b)=>{P.vertexAttribDivisor(a,b)},Ka:(a,b,c,d,e,f)=>{P.vertexAttribPointer(a,b,c,!!d,e,f)},Ja:(a,b,c,d)=>P.viewport(a,b,c,d),j:()=>0,ba:(a,b,c)=>Dd(a,{vf:t[c>>2],cf:t[c+4>>2],sg:t[c+8>>2],kg:b,Pe:t[c+12>>2],If:t[c+16>>2]}),G:(a,b)=>{a=Y(a);return a?a.requestPointerLock?Yc()?od(a):b?(Wc(od,2,[a]),1):-2:-1:-4},Fa:a=>{var b=p.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,
65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ma();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Ca:Ed,l:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Fd(a,b),y:(a,b,c,d)=>Gd(a,b,c,d,12,"blur"),c:gd,h:(a,b,c)=>{a=Y(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},z:(a,b,c,d)=>Gd(a,b,c,d,13,"focus"),o:(a,b,c,d)=>{if(!W.fullscreenEnabled())return-1;a=Y(a);if(!a)return-4;Hd(a,b,c,d,"webkitfullscreenchange");return Hd(a,
b,c,d,"fullscreenchange")},f:(a,b,c)=>Ed()?-1:Id(a,b,c,26,"gamepadconnected"),e:(a,b,c)=>Ed()?-1:Id(a,b,c,27,"gamepaddisconnected"),r:(a,b,c,d)=>Jd(a,b,c,d,2,"keydown"),p:(a,b,c,d)=>Jd(a,b,c,d,1,"keypress"),q:(a,b,c,d)=>Jd(a,b,c,d,3,"keyup"),Fd:(a,b,c)=>{a=z(a);Oc(a,b,c)},E:(a,b,c,d)=>Ld(a,b,c,d,5,"mousedown"),C:(a,b,c,d)=>Ld(a,b,c,d,33,"mouseenter"),B:(a,b,c,d)=>Ld(a,b,c,d,34,"mouseleave"),F:(a,b,c,d)=>Ld(a,b,c,d,8,"mousemove"),D:(a,b,c,d)=>Ld(a,b,c,d,6,"mouseup"),s:(a,b,c,d)=>document.body?.requestPointerLock?
(a=Y(a))?Md(a,b,c,d):-4:-1,n:(a,b,c,d)=>Nd(a,b,c,d),t:(a,b,c,d)=>Od(a,b,c,d,25,"touchcancel"),w:(a,b,c,d)=>Od(a,b,c,d,23,"touchend"),v:(a,b,c,d)=>Od(a,b,c,d,24,"touchmove"),x:(a,b,c,d)=>Od(a,b,c,d,22,"touchstart"),m:(a,b,c)=>Pd(a,b,c),A:(a,b,c,d)=>(a=Y(a))?"undefined"!=typeof a.onwheel?Qd(a,b,c,d):-1:-4,ca:a=>document.title=a?C(p,a):"",i:()=>{x("Please compile your program with async support in order to use asynchronous operations like emscripten_sleep")},id:(a,b)=>{var c=0,d=0,e;for(e of Td()){var f=
b+c;u[a+d>>2]=f;c+=D(e,p,f,Infinity)+1;d+=4}return 0},td:(a,b)=>{var c=Td();u[a>>2]=c.length;a=0;for(var d of c)a+=Ra(d)+1;u[b>>2]=a;return 0},k:a=>{ia=a;Mb(a)},u:function(a){try{var b=K(a);A.close(b);return 0}catch(c){if("undefined"==typeof A||"ErrnoError"!==c.name)throw c;return c.Wd}},ia:function(a,b,c,d){try{a:{var e=K(a);a=b;for(var f,g=b=0;g<c;g++){var l=u[a>>2],n=u[a+4>>2];a+=8;var q=A.read(e,m,l,n,f);if(0>q){var r=-1;break a}b+=q;if(q<n)break;"undefined"!=typeof f&&(f+=q)}r=b}u[d>>2]=r;return 0}catch(y){if("undefined"==
typeof A||"ErrnoError"!==y.name)throw y;return y.Wd}},T:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=K(a);A.be(e,b,c);qa[d>>3]=BigInt(e.position);e.jf&&0===b&&0===c&&(e.jf=null);return 0}catch(f){if("undefined"==typeof A||"ErrnoError"!==f.name)throw f;return f.Wd}},da:function(a,b,c,d){try{a:{var e=K(a);a=b;for(var f,g=b=0;g<c;g++){var l=u[a>>2],n=u[a+4>>2];a+=8;var q=A.write(e,m,l,n,f);if(0>q){var r=-1;break a}b+=q;if(q<n)break;"undefined"!=
typeof f&&(f+=q)}r=b}u[d>>2]=r;return 0}catch(y){if("undefined"==typeof A||"ErrnoError"!==y.name)throw y;return y.Wd}},Dc:Mb};function ae(a=[]){var b=ce;a.unshift(ba);var c=a.length,d=bd(4*(c+1)),e=d,f;for(f of a)u[e>>2]=cd(f),e+=4;u[e>>2]=0;try{var g=b(c,d);ia=g;Mb(g);return g}catch(l){return Lb(l)}}
function fe(a=aa){function b(){h.calledRun=!0;if(!ha){la=!0;if(!h.noFSInit&&!A.lf){var c,d;A.lf=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?A.ve("/dev","stdin",c):A.ze("/dev/tty","/dev/stdin");d?A.ve("/dev","stdout",null,d):A.ze("/dev/tty","/dev/stdout");e?A.ve("/dev","stderr",null,e):A.ze("/dev/tty1","/dev/stderr");A.open("/dev/stdin",0);A.open("/dev/stdout",1);A.open("/dev/stderr",1)}ge.Hd();A.Pf=!1;ja?.(h);h.onRuntimeInitialized?.();h.noInitialRun||ae(a);if(h.postRun)for("function"==typeof h.postRun&&
(h.postRun=[h.postRun]);h.postRun.length;){var e=h.postRun.shift();xa.push(e)}wa(xa)}}if(0<db)eb=fe;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)za();wa(ya);0<db?eb=fe:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var ge;
ge=await (async function(){function a(c){c=ge=c.exports;V=c.Id;ce=h._main=c.Jd;de=c.Ld;ed=c.Md;bd=c.Nd;dd=c.Od;na=c.Gd;Da=c.Kd;ma();return ge}var b={a:ee};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ra??=h.locateFile?h.locateFile("doomgeneric.wasm",ca):ca+"doomgeneric.wasm";return a((await ua(b)).instance)}());fe();la?moduleRtn=h:moduleRtn=new Promise((a,b)=>{ja=a;ka=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=createDoomModule;module.exports.default=createDoomModule}else if(typeof define==="function"&&define["amd"])define([],()=>createDoomModule);
