# Emscripten build for doomgeneric, replaces upstream Makefile.emscripten.
# Targets: a self-contained JS+WASM bundle suitable for an iframe.

ifeq ($(V),1)
	VB=''
else
	VB=@
endif

CC=emcc
SDL_PORTS=-sUSE_SDL=2 -sUSE_SDL_MIXER=2 -sSDL2_MIXER_FORMATS='["mid"]'

# -O3 + LTO is the standard "make wasm fast" recipe. ASSERTIONS=0 trims
# runtime checks. INITIAL_MEMORY=128MB avoids growth churn during play.
# -msimd128 + -mbulk-memory let the renderer's tight column/span loops
# auto-vectorize; --closure 1 minifies the JS glue.
WASM_FEATURES=-msimd128 -mbulk-memory
CFLAGS+=-O3 -flto $(WASM_FEATURES) -DFEATURE_SOUND $(SDL_PORTS)
LDFLAGS+=$(SDL_PORTS) \
	-O3 -flto $(WASM_FEATURES) \
	--closure 1 \
	--preload-file doom1.wad \
	-sALLOW_MEMORY_GROWTH=1 \
	-sINITIAL_MEMORY=128MB \
	-sASSERTIONS=0 \
	-sEXPORTED_RUNTIME_METHODS='["callMain","FS","ccall","cwrap"]' \
	-sEXPORT_ES6=0 \
	-sMODULARIZE=1 \
	-sEXPORT_NAME=createDoomModule \
	-sENVIRONMENT=web
LIBS+=-lm -lc

OBJDIR=build-web
OUTPUT=doomgeneric

SRC_DOOM = dummy.o am_map.o doomdef.o doomstat.o dstrings.o d_event.o d_items.o d_iwad.o d_loop.o d_main.o d_mode.o d_net.o f_finale.o f_wipe.o g_game.o hu_lib.o hu_stuff.o info.o i_cdmus.o i_endoom.o i_joystick.o i_scale.o i_sound.o i_system.o i_timer.o memio.o m_argv.o m_bbox.o m_cheat.o m_config.o m_controls.o m_fixed.o m_menu.o m_misc.o m_random.o p_ceilng.o p_doors.o p_enemy.o p_floor.o p_inter.o p_lights.o p_map.o p_maputl.o p_mobj.o p_plats.o p_pspr.o p_saveg.o p_setup.o p_sight.o p_spec.o p_switch.o p_telept.o p_tick.o p_user.o r_bsp.o r_data.o r_draw.o r_main.o r_plane.o r_segs.o r_sky.o r_things.o sha1.o sounds.o statdump.o st_lib.o st_stuff.o s_sound.o tables.o v_video.o wi_stuff.o w_checksum.o w_file.o w_main.o w_wad.o z_zone.o w_file_stdc.o i_input.o i_video.o doomgeneric.o doomgeneric_emscripten.o mus2mid.o i_sdlmusic.o i_sdlsound.o
OBJS += $(addprefix $(OBJDIR)/, $(SRC_DOOM))

all:	 $(OUTPUT)

clean:
	rm -rf $(OBJDIR)
	rm -f $(OUTPUT).js
	rm -f $(OUTPUT).data
	rm -f $(OUTPUT).wasm

$(OUTPUT):	$(OBJS)
	@echo [Linking $@]
	$(VB)$(CC) $(CFLAGS) $(LDFLAGS) $(OBJS) -o $(OUTPUT).js $(LIBS)

$(OBJS): | $(OBJDIR)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJDIR)/%.o:	%.c
	@echo [Compiling $<]
	$(VB)$(CC) $(CFLAGS) -c $< -o $@

print:
	@echo OBJS: $(OBJS)
